//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.SqlData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public int StockID { get; set; }
        public string StockName { get; set; }
        public string StockSymbol { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
    }
}
