//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.SqlData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts
    {
        public int UserID { get; set; }
        public int AccountID { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int AddedBy { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
